apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-system-passphrase-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    SYSTEM_PASSPHRASE: AgCcoZ6ZaSsFcPQQ+pl7Tc+VdPamTo3t+0x9mppxmgsd6CwUWODOtrfG7yJ+m4ZB/JTmfRemiH8975m86sFfVcXEHfEC/BMtAme11NYXpWGqCp2+KhdwpbxYVstRP5HCDs/72R9PJnmBM8VKzBWU3qB62Ll9kOBjvNF2i+a/OtcV46TwyNlhXdVj3qejXFBgJe/VWrZT5T5g1JPKbAp6Vr5d5sKG84YuiSh/FPG+AA+MloTR9UxfCVGBBuwJmGbb7uzb3su0wcLzyD+iEQIiixuS31jFpIEqe1j16xKsa3XtWOitUZnLEfON5htnB2UVLpdC3Ko9iR8BI1LZBDlUd2ZaRwwt/qDeJnoCfUGgMAE9nZNBxJ5NpfpTMBQVvImsilWVY8N6YkxYOmCz1kHVZ633ByX9RHzTqr12ueaTMufbEQ6ox5u0z1jjvkGF+4VKmX9TvoI1aSzSlIP8AFhdO8g/PsE8eJhJSzBjg5ko6orKYVPcj76QkDpEw+z00dnt8Q/qXTkmC9h4tA2FyHiya0NNN2Sa/x58CoTquPL0aWyfXN6O7Uol0Z09EwkcGlPkVI5edyhZw6xrKWuETbXHTutvVW10soSmQsdh1tDPlN/8kXvzJYe/iPTe8tK+FwpvUXn5NdFVPFEoNU3xsu3KJsXRbuz0pOIjCxxhptTlbZp1BbJ8uFgC6IvqcCY8BZ9TRshGEKIMCHChPg==
  template:
    metadata:
      creationTimestamp: null
      name: b2b-system-passphrase-secret
      namespace: b2bi-prod
    type: Opaque

